---
abstract: 'capture STDOUT and STDERR from Perl code, subprocesses or XS'
author:
  - 'David A. Golden <dagolden@cpan.org>'
build_requires:
  File::Spec: 3.27
  IO::File: 0
  Test::More: 0.62
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-CaptureOutput
no_index:
  directory:
    - examples
    - inc
provides:
  IO::CaptureOutput:
    file: lib/IO/CaptureOutput.pm
    version: 1.1102
requires:
  Carp: 0
  Exporter: 0
  File::Basename: 0
  File::Temp: 0.16
  Symbol: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dagolden/io-captureoutput.git
version: 1.1102
